server:
  port: 9001

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/users?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:/db/changelog/app-changelog.xml
  zipkin:
    base-url: http://127.0.0.1:9411/