version: "3"
services:
  mysqldb:
    image: mysql
    container_name: mysql-container
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: coffee_shop
      MYSQL_ROOT_PASSWORD: admin
  
  user-order-service:
    image: chirag407/user-order-service:v1
    container_name: user-order-service-container
    ports:
      - 8081:8080
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: admin